Allow simulating unimportable backends
I have both backends available in my test environment and use
QUTE_TESTS_BACKEND to pick a backend.

Since moving to qutebrowser/qt.py as a file instead of modules some
error cases show up as AttributeErrors at import time instead of ImportErrors.
In particular when you import a qutebrowser module like
webenginequtescheme and the webengine stuff in qt.py is None we get
errors like

    AttributeError: 'NoneType' object has no attribute 'QWebEngineUrlSchemeHandler'

when we import the qutebrowser module.

This is a way for me to make sure those errors show up for me even when
I have both backends available.